const adminMoney = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
function adminMessage(text,isError=false){const toast=document.querySelector("[data-admin-message]");toast.textContent=text;toast.classList.toggle("error",isError);toast.classList.add("visible");setTimeout(()=>toast.classList.remove("visible"),3500);}
async function adminRequest(url,options={}){const response=await fetch(url,options);const data=response.status===204?{}:await response.json();if(response.status===401||response.status===403){window.location.href=response.status===401?"login.html":"perfil.html";throw new Error("Acesso não autorizado.");}if(!response.ok)throw new Error(data.error||"Não foi possível salvar.");return data;}
async function loadAdmin(){const [me,contentResponse,products]=await Promise.all([adminRequest("/api/auth/me"),fetch("/api/content").then(r=>r.json()),adminRequest("/api/admin/products")]);if(me.user.role!=="admin")return window.location.href="perfil.html";const contentForm=document.querySelector("[data-content-form]");Object.entries(contentResponse).forEach(([key,value])=>{if(contentForm.elements[key])contentForm.elements[key].value=value;});document.querySelector("[data-admin-products]").innerHTML=products.map(product=>`
<form class="admin-product-card" data-product-form="${product.id}"><div class="admin-product-image"><img src="${product.image}" alt="${product.name}"><label class="image-upload">TROCAR IMAGEM<input type="file" name="image" accept="image/png,image/jpeg,image/webp"></label></div><div class="admin-product-fields"><span>${product.id}</span><label>Nome<input name="name" value="${product.name}" required></label><label>Linha<select name="line"><option ${product.line==="Essential"?"selected":""}>Essential</option><option ${product.line==="Black Label"?"selected":""}>Black Label</option></select></label><label>Descrição curta<input name="description" value="${product.description}" required></label><label>História da peça<textarea name="details" rows="4" required>${product.details}</textarea></label><div class="admin-product-numbers"><label>Preço<input name="price" type="number" min="0" step="0.01" value="${product.price}" required></label><label>Estoque<input name="remaining" type="number" min="0" step="1" value="${product.remaining}" required></label></div><label class="admin-check"><input name="active" type="checkbox" ${product.active?"checked":""}> Produto visível na loja</label><button class="btn btn-light" type="submit">SALVAR PRODUTO</button><small>Preço atual: ${adminMoney.format(product.price)}</small></div></form>`).join("");}
document.querySelector("[data-content-form]")?.addEventListener("submit",async event=>{event.preventDefault();try{await adminRequest("/api/admin/content",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});adminMessage("Textos da home atualizados.");}catch(error){adminMessage(error.message,true);}});
document.addEventListener("submit",async event=>{const form=event.target.closest("[data-product-form]");if(!form)return;event.preventDefault();const id=form.dataset.productForm;const values=Object.fromEntries(new FormData(form));values.price=Number(values.price);values.remaining=Number(values.remaining);values.active=form.elements.active.checked;delete values.image;try{await adminRequest(`/api/admin/products/${encodeURIComponent(id)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const imageFile=form.elements.image.files[0];if(imageFile){const imageData=new FormData();imageData.append("image",imageFile);const result=await adminRequest(`/api/admin/products/${encodeURIComponent(id)}/image`,{method:"POST",body:imageData});form.querySelector("img").src=result.image;form.elements.image.value="";}adminMessage(`${values.name} atualizado.`);}catch(error){adminMessage(error.message,true);}});
document.querySelector("[data-logout]")?.addEventListener("click",async()=>{await fetch("/api/auth/logout",{method:"POST"});window.location.href="index.html";});
loadAdmin().catch(error=>adminMessage(error.message,true));
