const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}),freight=24.90;let products=window.CULT_PRODUCTS||[];
function getCart(){try{const c=JSON.parse(localStorage.getItem("cult-cart")||"[]");return Array.isArray(c)?c:[];}catch{return[];}}
function setCart(c){localStorage.setItem("cult-cart",JSON.stringify(c));updateCartCount();}
function updateCartCount(){const n=getCart().reduce((s,x)=>s+x.quantity,0);document.querySelectorAll("[data-cart-count]").forEach(e=>e.textContent=String(n));}
const findProduct=id=>products.find(p=>p.id===id);
async function loadProducts(){try{const r=await fetch("/api/products");if(r.ok)products=await r.json();}catch{}}
async function loadContent(){try{const r=await fetch("/api/content"),c=await r.json();document.querySelectorAll("[data-content]").forEach(e=>{if(typeof c[e.dataset.content]==="string")e.textContent=c[e.dataset.content];});}catch{}}
async function accountNav(){const nav=document.querySelector(".site-header .nav");if(!nav||nav.querySelector("[data-account-link]"))return;const a=document.createElement("a");a.dataset.accountLink="";a.href="login.html";a.textContent="Entrar";try{const r=await fetch("/api/auth/me");if(r.ok){const {user}=await r.json();a.href="perfil.html";a.textContent=user.role==="admin"?"Admin":"Perfil";}}catch{}nav.insertBefore(a,nav.lastElementChild);}
function renderCatalog(){document.querySelectorAll("[data-catalog]").forEach(g=>g.innerHTML=products.filter(p=>p.line===g.dataset.catalog).map(p=>`<article class="product-card ${p.line==="Black Label"?"luxury":""}"><a href="produto.html?id=${encodeURIComponent(p.id)}"><img src="${p.image}" alt="${p.name}"></a><div class="info"><span>${p.line.toUpperCase()}</span><h3>${p.name}</h3><p>${p.description}</p><strong>${money.format(p.price)}</strong><em>RESTAM ${p.remaining} PEÇAS</em><a href="produto.html?id=${encodeURIComponent(p.id)}">VER PEÇA</a></div></article>`).join(""));}
function renderProduct(){const c=document.querySelector("[data-product-detail]");if(!c||!products.length)return;const p=findProduct(new URLSearchParams(location.search).get("id")||"black-001")||products[0];document.title=`CultStreet | ${p.name}`;c.innerHTML=`<div class="product-photo"><img src="${p.image}" alt="${p.name}"></div><div class="product-copy"><span>${p.line}</span><h1>${p.name}</h1><p>${p.details}</p><strong>${money.format(p.price)}</strong><label>Tamanho</label><div class="size-options" data-size-options><button type="button" data-size="P">P</button><button type="button" data-size="M" class="selected">M</button><button type="button" data-size="G">G</button><button type="button" data-size="GG">GG</button></div><label>Quantidade</label><input class="qty-input" type="number" min="1" max="${p.remaining}" value="1" data-quantity><button class="btn btn-light" type="button" data-add-cart="${p.id}">ADICIONAR AO CARRINHO</button><a class="btn btn-dark" href="checkout.html">IR PARA CHECKOUT</a><div class="detail-list"><p><b>Linha:</b> ${p.line}</p><p><b>Quantidade restante:</b> ${p.remaining} peças</p></div></div>`;}
function addCart(id){const p=findProduct(id);if(!p)return;const size=document.querySelector("[data-size-options] .selected")?.dataset.size||"M",quantity=Math.min(p.remaining,Math.max(1,Math.floor(Number(document.querySelector("[data-quantity]")?.value||1)))),cart=getCart(),old=cart.find(x=>x.id===id&&x.size===size);old?old.quantity+=quantity:cart.push({id,size,quantity});setCart(cart);alert("Peça CultStreet adicionada ao carrinho.");}
function totals(subtotal){const shipping=subtotal>0?freight:0;return `<div><span>Subtotal</span><strong>${money.format(subtotal)}</strong></div><div><span>Frete</span><strong>${money.format(shipping)}</strong></div><div class="grand-total"><span>Total</span><strong>${money.format(subtotal+shipping)}</strong></div>`;}
function renderCheckout(){const list=document.querySelector("[data-cart-list]"),t=document.querySelector("[data-cart-totals]");if(!list||!t)return;const cart=getCart().filter(x=>findProduct(x.id));if(!cart.length){list.innerHTML='<p class="empty-cart">Seu carrinho está vazio.</p>';t.innerHTML=totals(0);return;}list.innerHTML=cart.map((x,i)=>{const p=findProduct(x.id);return `<article class="cart-row"><img src="${p.image}" alt="${p.name}"><div><span>${p.line}</span><h2>${p.name}</h2><p>Tamanho: ${x.size} | Quantidade: ${x.quantity}</p><strong>${money.format(p.price*x.quantity)}</strong></div><button type="button" data-remove="${i}">Remover</button></article>`;}).join("");t.innerHTML=totals(cart.reduce((s,x)=>s+findProduct(x.id).price*x.quantity,0));}
document.addEventListener("click",e=>{const s=e.target.closest("[data-size]");if(s){document.querySelectorAll("[data-size]").forEach(b=>b.classList.remove("selected"));s.classList.add("selected");}const a=e.target.closest("[data-add-cart]");if(a)addCart(a.dataset.addCart);const r=e.target.closest("[data-remove]");if(r){const c=getCart();c.splice(Number(r.dataset.remove),1);setCart(c);renderCheckout();}});
document.querySelector("[data-checkout-form]")?.addEventListener("submit",async e=>{e.preventDefault();const cart=getCart();if(!cart.length)return alert("Seu carrinho está vazio.");const b=e.currentTarget.querySelector('button[type="submit"]'),f=new FormData(e.currentTarget);b.disabled=true;b.textContent="ABRINDO MERCADO PAGO...";try{const r=await fetch("/create-preference",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart,payer:{email:f.get("email")}})}),d=await r.json();if(!r.ok||!d.init_point)throw Error(d.error||"Não foi possível iniciar o pagamento.");location.href=d.init_point;}catch(err){alert(err.message);b.disabled=false;b.textContent="FINALIZAR COMPRA";}});
document.querySelector("[data-contact-form]")?.addEventListener("submit",e=>{e.preventDefault();alert("Mensagem recebida. A equipe CultStreet entrará em contato.");e.currentTarget.reset();});
(async()=>{updateCartCount();await Promise.all([loadProducts(),loadContent(),accountNav()]);renderCatalog();renderProduct();renderCheckout();})();
